### ISSUE TITLE
1.3.1 / 10.12.6/ EXC_BAD_INSTRUCTION (SIGILL) / Illegal instruction: 4

### ISSUE THREAD

**Issue by joeMJ** [volendavidov/NagBar#2] opened 2017-09-19 17:14 UTC
Hi Volen,

I got some strange crashs with the 1.3.1 - occurs while change state from critical to normal or vice versa. Please find crashlog as attachment.
[NagBar_2017-09-19-141901_Johns-BigMac.crash.zip](https://github.com/volendavidov/NagBar/files/1315178/NagBar_2017-09-19-141901_Johns-BigMac.crash.zip)

Monitoring 2x status.cgi classic nagios.

Regards,
John

**Comment by volendavidov** [comment] 2017-09-19 19:54
Hi John,

It looks like a bug with the HTML parser. Is it possible to provide me with obfuscated data from `status.cgi` at the time of the crash? Probably there is something in the structure of the HTML that the parser does not process correctly.

Regards,
Volen

**Comment by joeMJ** [comment] 2017-09-20 16:50
Hi Volen,

unfortunately September patchday is over ;-) So here's a "guess" based on "we had that already", you know ;-)? I'm not allowed to stop this special service outside patch time slots to reproduce. 

This is Nagios trying to display german "Umlaut" "ä"/"ö"/"ü". Should display "Domänendienste" but doesn't. In addition I'm not allowed to patch this special monitoring node. 

This is what Nagios displays: "Active Directory-Dom䮥ndienste: running (start type is auto)"

Regards,
John

**Comment by volendavidov** [comment] 2017-09-26 19:16
Hi John,

I tried reproducing the problem, but it doesn't crash on my end with characters which are not rendered properly (btw, umlauts are displayed fine on my Nagios, strange why it doesn't work for you). Here is a screenshot:

![screenshot2](https://user-images.githubusercontent.com/20255349/30879349-d8663584-a307-11e7-957a-3187c392deab.png)

Whenever you have the chance, can you paste me the HTML code from the Nagios page for the service and more specifically, the status information. I.e. the following part:

`<TR><TD CLASS='dataVar' VALIGN='top'>Status Information:</TD><TD CLASS='dataVal'>Active Directory-Dom&#19365;ndienste: running (start type is auto)</TD></TR>` 

Regards,
Volen

**Comment by volendavidov** [comment] 2019-02-10 19:07
No update here - closing for the moment.

**Closed as completed by volendavidov** 2019-02-10 19:07 UTC
